### ISSUE TITLE
How to use these scripts for linux

### ISSUE THREAD

**Issue by Hippogriff** [AntonOvsyannikov/PyOpenGL_Examples_SaveToFile#1]
I want to do some rendering on Slurm based cluster that run linux. I cannot open a window as there is no x11 server. Can you suggest ways in which I can use your scripts in linux. More specifically alternatives to these packages:

    from LibGL.Win32 import *
    from LibGL.Context import *
    from LibGL.Buffers import *

**Comment by Hippogriff** [comment]
I found the solution using osmesa.

**Comment by nostayup** [comment]
hello，An error occurred while running the program，“ModuleNotFoundError: No module named 'PFD'”，what is PFD？thanks~
